export const cars = [
   //toyta
   [
      {
         name: 'toyta',
         id: 1,
         model: 'Land Cruiser 200',
         year: '2008-2021',
         price: 12000,
         banner: './img/baner/t1.jpg',
      },

      {
         name: 'toyta',
         id: 2,
         model: 'Land Cruiser 100-105 (Lx470)',
         year: '1997-2007',
         price: 12000,
         banner: './img/baner/t2.jpg',
      },
      {
         name: 'toyta',
         id: 3,
         model: 'PRADO 120 (GX470)',
         year: '2002-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 4,
         model: 'PRADO 150 (GX460)',
         year: '2009-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 5,
         model: 'Land Cruiser 95',
         year: '1990-1997',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 6,
         model: 'Land Cruiser 300',
         year: '2021-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 7,
         model: 'Camry 70-75',
         year: '2017-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 8,
         model: 'Camry 55 Американец',
         year: '2014-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 9,
         model: 'Camry 50-55',
         year: '2011-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 10,
         model: 'Camry 40-45',
         year: '2006-2011',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 11,
         model: 'Camry 30-35',
         year: '2001-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 12,
         model: 'Camry 20-25',
         year: '1994-2001',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 13,
         model: 'Camry 10-15',
         year: '1991-1996',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 14,
         model: 'HILUX',
         year: '2004-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 15,
         model: 'Fortuner',
         year: '2004-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 16,
         model: 'HILUX New',
         year: '2015-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 17,
         model: 'Fortuner New',
         year: '2015-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 18,
         model: 'AVALON 05',
         year: '2005-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 19,
         model: 'T.AVALON 12',
         year: '2012-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 20,
         model: 'Avensis 03',
         year: '2003-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 21,
         model: 'Avensis 09',
         year: '2009-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 22,
         model: 'ALPHARD 02',
         year: '2002-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 23,
         model: 'ALPHARD 2008',
         year: '2008-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 24,
         model: 'ALPHARD 2022',
         year: '2016-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 25,
         model: 'Highlander',
         year: '2001-2007',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 26,
         model: 'Highlander',
         year: '2007-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         //вопросик
         name: 'toyta',
         id: 27,
         model: 'Venza',
         year: '2008-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 28,
         model: 'Highlander',
         year: '2013-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 29,
         model: 'Kluger',
         year: '2013-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 30,
         model: 'Highlander 20',
         year: '2020-2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 31,
         model: '4Runner',
         year: '2002-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 32,
         model: '4Runner',
         year: '2009-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 33,
         model: 'RAV-4',
         year: '2005-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 34,
         model: 'RAV-4',
         year: '2013-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 35,
         model: 'RAV-4',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 36,
         model: 'COROLLA E120',
         year: '2000-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 37,
         model: 'COROLLA E150',
         year: '2006-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 38,
         model: 'COROLLA E160',
         year: '2013-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 39,
         model: 'COROLLA E170',
         year: '2013-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 40,
         model: 'COROLLA Е210 ',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 41,
         model: 'SIENNA 03',
         year: '2003-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 42,
         model: 'SIENNA 10',
         year: '2010-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 43,
         model: 'Ipsum',
         year: '2001-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 44,
         model: 'Fj Cruiser ',
         year: '2006-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 45,
         model: 'hiace',
         year: '2004-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 46,
         model: 'hiace',
         year: '2019-2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 47,
         model: 'CARINA E',
         year: '1992-1998',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 48,
         model: ' CORONA ',
         year: '1992-1998',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 49,
         model: 'Windom XV30 / ES300-330',
         year: '2001-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 50,
         model: 'Estima',
         year: '2001-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 51,
         model: 'Estima XR50 ',
         year: '2006-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 52,
         model: 'Tundra',
         year: '2007-2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 53,
         model: 'Tacoma',
         year: '2005-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 54,
         model: 'SELSIOR',
         year: '2000-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 55,
         model: 'Windom XV20',
         year: '2001-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 56,
         model: 'Mark 2 (90)',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 57,
         model: 'Mark 2 (100)',
         year: '1996-2000',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 58,
         model: 'Mark 2 (110)',
         year: '2000-2007',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 59,
         model: 'MAJESTA 186',
         year: '2004-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 60,
         model: 'Matrix',
         year: '2002-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 61,
         model: 'CROWN',
         year: '2008-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 62,
         model: 'CROWN  retro перед и зад двери',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 63,
         model: 'PRIUS 20',
         year: '2003-2011',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'toyta',
         id: 64,
         model: 'VERSO',
         year: '2009-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      // {
      //    name: 'toyta',
      //    id: 54,
      //    model: 'Venza',
      //    year: '2008-2017',
      //    price: 12000,
      // },
   ],
   //lexus
   [
      {
         name: 'lexus',
         id: 1,
         model: 'LX570',
         year: '2007-2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 2,
         model: 'es300-330 / WINDOM XV30',
         year: '2001-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 3,
         model: 'LS430',
         year: '2000-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 4,
         model: 'es350/gs',
         year: '2006-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 5,
         model: 'es 12-18',
         year: '2012-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 6,
         model: 'es 19-22',
         year: '2019-2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 7,
         model: 'gs300 (160)',
         year: '1997-2005',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 8,
         model: 'gs300-350 (190)',
         year: '2005-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 9,
         model: 'gs 12-',
         year: '2012+/ES350 2006+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 10,
         model: 'IS 06-12',
         year: '2006-2012',
         price: 12000,
      },
      {
         name: 'lexus',
         id: 11,
         model: 'IS 13-16',
         year: '2013-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 12,
         model: 'NX200',
         year: '2014-2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 13,
         model: 'NX300',
         year: '2014-2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 14,
         model: 'RX300 ',
         year: '2014-2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 15,
         model: 'RX 330',
         year: '2014-2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 16,
         model: 'RX 350',
         year: '2014-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 17,
         model: 'LS460',
         year: '2006-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 18,
         model: 'CT200H',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lexus',
         id: 19,
         model: 'RX 300-350',
         year: '2016-2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //mb
   [
      {
         name: 'mercedesbenz',
         id: 1,
         model: 'Gelendewagen (G-class)',
         year: '1990-2022',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },

      {
         name: 'mercedesbenz',
         id: 2,
         model: 'W 140 (S-class)',
         year: '1991-1998',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 3,
         model: 'W 210 (E-class)',
         year: '1995-2002',
         price: 2000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 4,
         model: 'W 210 задние даери',
         year: '1995-2002',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 5,
         model: 'W 211 (E-class)',
         year: '2002-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 6,
         model: 'W 212 (E-class)',
         year: '2009-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 7,
         model: 'W 220 (S-class)',
         year: '1998-2005',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 8,
         model: 'W 221 (S-class)',
         year: '2005-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 9,
         model: 'W 222 (S-class)',
         year: '2013-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 10,
         model: 'W 202 (C-class)',
         year: '1993-2001',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 11,
         model: 'W 203 (C-class)',
         year: '2000-2007',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 12,
         model: 'W 204 (C-class)',
         year: '2004-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 13,
         model: 'GLS',
         year: '2006-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 14,
         model: 'W 124 (E-class)',
         year: '1984-1995',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 15,
         model: 'A170',
         year: '2004-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 16,
         model: 'W 140  (S-class) задние двери',
         year: '2004-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 17,
         model: 'W 220 задние двери',
         year: '2004-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 18,
         model: 'W205',
         year: '2014-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mercedesbenz',
         id: 19,
         model: 'CLS63',
         year: '2014-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //bmw
   [
      {
         name: 'bmw',
         id: 1,
         model: 'X5 E53',
         year: '1996-2006',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 2,
         model: 'X5 Е70',
         year: '2006-2013',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 3,
         model: 'E34',
         year: '1992-1996',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 4,
         model: 'E38',
         year: '1994-2001',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 5,
         model: 'E39',
         year: '1995-2003',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 6,
         model: 'E46',
         year: '1998-2007',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 7,
         model: 'E60',
         year: '2002-2010',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 8,
         model: 'E61',
         year: '2002-2010',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 9,
         model: 'E65',
         year: '2001-2008',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 10,
         model: 'E66',
         year: '2001-2008',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 11,
         model: 'F30',
         year: '2012-2016',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 12,
         model: 'E34 задние двери',
         year: '1992-1996',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 12,
         model: 'i840',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 13,
         model: 'X7',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 14,
         model: 'E34 задние двери',
         year: '1992-1996',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 15,
         model: 'E38 задние двери',
         year: '1994-2001',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 16,
         model: 'F10-11',
         year: '2010-2017',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 17,
         model: 'F30',
         year: '2012-2016',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 18,
         model: 'F32 КУПЕ',
         year: '2012-2016',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
      {
         name: 'bmw',
         id: 19,
         model: 'G30',
         year: '2017-2023',
         price: 12000,
         banner: './img/baner/msd1.jpg',
      },
   ],
   //audi
   [
      {
         name: 'audi',
         id: 1,
         model: '100',
         year: '1991-1997',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'audi',
         id: 2,
         model: 'A6 (C4)',
         year: '1991-1997',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'audi',
         id: 3,
         model: 'A8',
         year: '1994-2002',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'audi',
         id: 4,
         model: 'Q7',
         year: '2006-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'audi',
         id: 5,
         model: 'A6 (C5)',
         year: '1997-2004',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'audi',
         id: 6,
         model: 'A6 (C6)',
         year: '2005-2011',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'audi',
         id: 7,
         model: 'A8',
         year: '2009-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      // {
      //    name: 'audi',
      //    id: 7,
      //    model: '	Audi 80 b4',
      //    year: '',
      //    price: 12000,
      // },
   ],
   //kia
   [
      {
         name: 'kia',
         id: 1,
         model: 'K7',
         year: '2016-2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 2,
         model: 'K5',
         year: '2020-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 3,
         model: 'RIO',
         year: '2011-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 4,
         model: 'RIO NEW',
         year: '2017-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 5,
         model: 'SPORTAGE ',
         year: '2010-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 6,
         model: 'SPORTAGE',
         year: '2016-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 7,
         model: 'SPORTAGE NEW',
         year: '2021-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 8,
         model: 'CADENZA',
         year: '2009-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 9,
         model: 'SORENTO PRIME',
         year: '2014-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 10,
         model: 'SORENTO',
         year: '2002-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 11,
         model: 'SORENTO',
         year: '2009-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 12,
         model: 'SORENTO ',
         year: '2020-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 13,
         model: 'SOUL',
         year: '2014-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 14,
         model: 'SOUL',
         year: '2020-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 15,
         model: 'CEED',
         year: '2012-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 16,
         model: 'CERATO II',
         year: '2008-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 17,
         model: 'CERATO III',
         year: '2013-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 18,
         model: 'CERATO IV',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 19,
         model: 'OPTIMA',
         year: '2010-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 20,
         model: 'OPTIMA',
         year: '2016-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 21,
         model: 'MOHAVE',
         year: '2008+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 22,
         model: 'K8',
         year: '2021-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 23,
         model: 'K9/QUARIS',
         year: '2014-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 24,
         model: 'rio',
         year: '2005-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 25,
         model: 'PEGAS',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'kia',
         id: 26,
         model: 'CEED',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //hendai
   [
      {
         name: 'hyundai',
         id: 1,
         model: 'Sonata',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/hy1.jpg',
      },

      {
         name: 'hyundai',
         id: 2,
         model: 'ACCENT',
         year: '2010-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 3,
         model: 'Accent NEW',
         year: '2017-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 4,
         model: 'Elantra',
         year: '2010-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 5,
         model: 'Avante',
         year: '2010-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 6,
         model: 'Elantra',
         year: '2016-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 7,
         model: 'Elantra',
         year: '2021-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 8,
         model: 'Grandeur',
         year: '2005-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 9,
         model: 'GETZ',
         year: '2002-2011',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 10,
         model: 'Santa-fe ',
         year: '2006-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 11,
         model: 'Santa-fe',
         year: '2012-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 12,
         model: 'Santa-fe',
         year: '2019-2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 13,
         model: 'Palisade',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 14,
         model: 'Tucson',
         year: '2004-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 15,
         model: 'TUCSON-IX35',
         year: '2009-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 16,
         model: 'Tucson',
         year: '2015-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 17,
         model: 'Tucson  ',
         year: '2021-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 18,
         model: 'Sonata',
         year: '2001-2004',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 19,
         model: 'Sonata',
         year: '2004-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 20,
         model: 'Sonata',
         year: '2009-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 21,
         model: 'Sonata',
         year: '2014-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 22,
         model: 'ACCENT',
         year: '2001-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 23,
         model: 'I40',
         year: '2011-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 24,
         model: 'CRETA',
         year: '2015-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 25,
         model: 'Creta ',
         year: '2020-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 26,
         model: 'H1 Starex',
         year: '1997-2004',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 27,
         model: 'H1 Starex',
         year: '1996-н.в.',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 27,
         model: 'Staria',
         year: '2021-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 28,
         model: 'BAYON перед и зад дверь и окошко',
         year: '2023+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 29,
         model: 'Elantra/Avante',
         year: '2006-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 30,
         model: 'Grandeur',
         year: '2017-2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 31,
         model: 'I30',
         year: '2020-2024',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 32,
         model: 'I40 задние двери',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'hyundai',
         id: 33,
         model: 'Venue',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //honda
   [
      {
         name: 'honda',
         id: 1,
         model: 'ODYSSEY',
         year: '2005-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'honda',
         id: 2,
         model: 'ODYSSEY',
         year: '2011+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'honda',
         id: 3,
         model: 'ELYSION',
         year: '2004+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'honda',
         id: 4,
         model: 'CRV',
         year: '1995-2001',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'honda',
         id: 5,
         model: 'Accord',
         year: '2007-2011',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //mitsubishi
   [
      {
         name: 'mitsubishi',
         id: 1,
         model: 'Delica',
         year: '1994-2005',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 2,
         model: 'Pajero 2',
         year: '1991-2000',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 3,
         model: 'Pajero 3',
         year: '1999-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 4,
         model: 'Pajero sport',
         year: '2008-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 5,
         model: 'Pajero sport',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 6,
         model: 'Montero sport',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 7,
         model: 'Montero sport',
         year: '1997-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 8,
         model: 'Nativa',
         year: '1997-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 9,
         model: 'L200',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 10,
         model: 'Outlander',
         year: '2005-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 11,
         model: 'Outlander2',
         year: '2013-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 12,
         model: 'ASX',
         year: '2010-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 13,
         model: 'Lancer',
         year: '2007-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'mitsubishi',
         id: 14,
         model: 'Pajero 4',
         year: '2006-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 15,
         model: 'L200',
         year: '1997-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 16,
         model: 'Outlander sport',
         year: '2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 17,
         model: 'Delica кирпич',
         year: '1986-1993',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mitsubishi',
         id: 18,
         model: 'Lancer X',
         year: '2007-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //nissan
   [
      {
         name: 'nissan',
         id: 1,
         model: 'Teana j32',
         year: '2008-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 2,
         model: 'Teana j31',
         year: '2003-2008',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 3,
         model: 'Teana j33',
         year: '2014+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 4,
         model: 'TIDA',
         year: '2004-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 5,
         model: 'maxima A32',
         year: '1994-2000',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 6,
         model: 'Cefiro A32',
         year: '1994-1998',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 7,
         model: 'Cefiro A33',
         year: '1998-2003',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      // {
      //    name: 'nissan',
      //    id: 7,
      //    model: 'Infiniti I30	',
      //    year: '1994-2000',
      //    price: 12000,
      // },
      {
         name: 'nissan',
         id: 8,
         model: 'maxima A33',
         year: '1999-2003',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 9,
         model: 'almera classic ',
         year: '2006-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 10,
         model: 'Almera G15',
         year: '2012-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 11,
         model: 'Patrol Y61',
         year: '1997-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 12,
         model: 'Patrol Y62',
         year: '2010-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'nissan',
         id: 13,
         model: 'INFINITY QX 56',
         year: '010-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 14,
         model: 'INFINITY QX 80',
         year: '2013-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 15,
         model: 'ARMADA',
         year: '2003-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 16,
         model: 'INFINITY   QX56',
         year: '2004-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 17,
         model: 'Pathfinder R51',
         year: '2005-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 18,
         model: 'Qashqai 21',
         year: '2021-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 19,
         model: 'QUEST',
         year: '2011-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 20,
         model: 'Sentra',
         year: '2014-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 21,
         model: 'X-Terra',
         year: '2005-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 22,
         model: 'X-Trail',
         year: '2007-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 23,
         model: 'INFINITY   FX35  45 (S50)',
         year: '2002-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 24,
         model: 'Infiniti I30',
         year: '2002-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 25,
         model: 'ALMERA',
         year: '1995-2000',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'nissan',
         id: 26,
         model: 'FX35',
         year: '2008-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //vwgn
   [
      {
         name: 'volkswagen',
         id: 1,
         model: 'POLO',
         year: '2010-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 2,
         model: 'POLO NEW',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 3,
         model: 'PASSAT B3',
         year: '1988-1996',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 4,
         model: 'PASSAT B5',
         year: '1996-2005',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 5,
         model: 'PASSAT B6',
         year: '2005-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 6,
         model: 'TOUAREG',
         year: '2002-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 7,
         model: 'PORSCHE CAYENNE',
         year: '2002-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 8,
         model: 'VW PASSAT B7 USA',
         year: '2011-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 9,
         model: ' GOLF 3',
         year: '1991-2002',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 10,
         model: ' GOLF 4',
         year: '1997-2010',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'volkswagen',
         id: 11,
         model: 'PASSAT B4',
         year: '1988-1996',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'volkswagen',
         id: 12,
         model: 'PASSAT B7 USA',
         year: '2011-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 13,
         model: 'SHARAN / FORD GALAXY',
         year: '1996',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'volkswagen',
         id: 14,
         model: ' GOLF 6',
         year: '2008-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //renault
   [
      {
         name: 'renault',
         id: 1,
         model: 'Duster',
         year: '2009-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'renault',
         id: 2,
         model: 'Logan',
         year: '2012-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'renault',
         id: 3,
         model: 'ARKANA',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //skoda
   [
      {
         name: 'skoda',
         id: 1,
         model: 'RAPID',
         year: '2012-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'skoda',
         id: 2,
         model: 'OCTAVIA  A5',
         year: '2004-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'skoda',
         id: 3,
         model: 'OCTAVIA  A7',
         year: '2013-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'skoda',
         id: 4,
         model: 'SUPERB',
         year: '2008-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //CHEVRALET
   [
      {
         name: 'chevralet',
         id: 1,
         model: 'Cruze',
         year: '2008-2015',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 2,
         model: 'TAHOE',
         year: '2006-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 3,
         model: 'EQUINOX',
         year: '2021',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 4,
         model: 'ONIX',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 5,
         model: 'Niva',
         year: '2002-2009',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 6,
         model: 'Captiva',
         year: '2006-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 7,
         model: 'Aveo T250',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 8,
         model: 'Nexia Ravon R3',
         year: '2020-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 9,
         model: 'Malibu',
         year: '2011-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 10,
         model: 'Cobalt',
         year: '2012-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 11,
         model: 'RAVON R4',
         year: '2012-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 12,
         model: 'TAHOE',
         year: '2014-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 13,
         model: 'Chevralet Suburban',
         year: '2007-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'chevralet',
         id: 13,
         model: 'MONZA',
         year: '2019-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //lada
   [
      {
         name: 'lada',
         id: 1,
         model: 'priora',
         year: '2007+',
         price: 12000,
         banner: './img/baner/ru1.jpg',
      },

      {
         name: 'lada',
         id: 2,
         model: '2107',
         year: '1982-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 3,
         model: 'Largus',
         year: '2012-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 4,
         model: 'Granta',
         year: '2011-2017',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 5,
         model: 'Калина',
         year: '2004-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 6,
         model: 'Нива',
         year: '1977-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 7,
         model: 'Нива Урбан',
         year: '1977-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 8,
         model: 'Vesta',
         year: '2015+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 9,
         model: 'X-RAY',
         year: '2015+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 10,
         model: 'Газель Бизнес',
         year: '1994-2013',
         price: 14000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 11,
         model: 'Газель NEXT',
         year: '2013-н.в.',
         price: 14000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 12,
         model: 'УАЗ буханка',
         year: '1985+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 13,
         model: 'УАЗ ПАТРИОТ',
         year: '2012-2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 14,
         model: '2114-2115',
         year: '2001-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'lada',
         id: 15,
         model: 'КАМАЗ',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],

   //opel
   [
      {
         name: 'opel',
         id: 1,
         model: 'OPEL ZAFIRA A',
         year: '1999-2005',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'opel',
         id: 2,
         model: 'OPEL ZAFIRA B',
         year: '2005-2011',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'opel',
         id: 3,
         model: 'OPEL ASTRA G',
         year: '1998-2004',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'opel',
         id: 4,
         model: 'Opel Vectra',
         year: '1988-1995',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'opel',
         id: 5,
         model: 'Opel Vectra',
         year: '1995-2002',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //subaru
   [
      {
         name: 'subaru',
         id: 1,
         model: 'Subaru Outback 09',
         year: '2009-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'subaru',
         id: 2,
         model: 'Subaru Outback 15',
         year: '2015-2020',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'subaru',
         id: 3,
         model: 'Subaru Tribecca	',
         year: '2005-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'subaru',
         id: 4,
         model: 'Subaru forester 08',
         year: '	2008-2012',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'subaru',
         id: 5,
         model: 'Subaru forester 12',
         year: '2012-2018',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'subaru',
         id: 6,
         model: 'Subaru forester 18',
         year: '2018+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'subaru',
         id: 7,
         model: 'Legacy',
         year: '2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //DAEWOO
   [
      {
         name: 'daewoo',
         id: 1,
         model: 'Nexia 1-2',
         year: '1994-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'daewoo',
         id: 2,
         model: 'Gentra',
         year: '2013-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'daewoo',
         id: 3,
         model: 'matiz',
         year: '1998-2005',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //mazda
   [
      {
         name: 'mazda',
         id: 1,
         model: 'Mazda MPV',
         year: '2000-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mazda',
         id: 2,
         model: 'MAZDA 6',
         year: '2002-2007',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mazda',
         id: 3,
         model: 'MAZDA 626 cronos',
         year: '1991-1997',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mazda',
         id: 4,
         model: 'MAZDA 626 ',
         year: '1987-1997',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'mazda',
         id: 5,
         model: 'MAZDA птичка',
         year: '1997-2002',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //китайцы
   [
      {
         name: 'Chinese',
         id: 1,
         model: 'EXEED LX',
         year: '2021-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 2,
         model: 'EXEED VX',
         year: '2021-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 3,
         model: 'Chery 7-8 PRO',
         year: '2019-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 4,
         model: 'Jac S5',
         year: '2013+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 5,
         model: 'LIFAN х60',
         year: '2012-2016',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'Chinese',
         id: 6,
         model: 'GREAT WALL',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'Chinese',
         id: 7,
         model: 'Geely Emgrand X',
         year: '2011-2019',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 8,
         model: 'Jetour X70',
         year: '2018-2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 9,
         model: 'AVATR',
         year: '2023+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 10,
         model: 'OMODA S5',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 11,
         model: 'OMODA C5',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 12,
         model: 'CHANGAN CS55+',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 13,
         model: 'Chery 2 PRO',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 13,
         model: 'Chery 4 PRO',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 14,
         model: 'CHANGAN UNI-V',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 15,
         model: 'HAVAL JOLION',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 16,
         model: 'HAVAL H6',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 17,
         model: 'HAVAL DARGO',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 18,
         model: 'TANK 500',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 19,
         model: 'TANK 300',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 20,
         model: 'Jac J7',
         year: '2020-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 21,
         model: 'JAC JS6',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 22,
         model: 'JAC S3',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 23,
         model: 'Li 7 ЗАДНИЕ ДВЕРИ',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 24,
         model: 'GEELY MONJARO',
         year: '2022',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 25,
         model: 'Geely Emgrand',
         year: '2023',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Chinese',
         id: 26,
         model: 'GEELY OKAVANGO',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
   ],
   //Americans
   [
      {
         name: 'Americans',
         id: 1,
         model: 'Cadillac Escalade',
         year: '2002-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Americans',
         id: 2,
         model: 'Cadillac Escalade',
         year: '2007-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      // {
      //    name: 'Americans',
      //    id: 12,
      //    model: 'Chevralet Tahoe',
      //    year: '2007-2013',
      //    price: 12000,
      // },
      {
         name: 'Americans',
         id: 3,
         model: 'GMC Yukon',
         year: '2007-2013',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'remAmericansain',
         id: 4,
         model: 'Cadillac Escalade ',
         year: '2015+',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'Americans',
         id: 5,
         model: 'Hammer H2',
         year: '',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'Americans',
         id: 6,
         model: 'ACURA MDX',
         year: '2001-2006',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      {
         name: 'Americans',
         id: 7,
         model: 'LINCOLN MARK 8',
         year: '1991',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Americans',
         id: 8,
         model: 'PEJO 301-302',
         year: '1991',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Americans',
         id: 9,
         model: 'FORD F150',
         year: '2008-2014',
         price: 12000,
         banner: './img/baner/all.jpg',
      },
      {
         name: 'Americans',
         id: 10,
         model: 'FORD GALAXY',
         year: '1995-',
         price: 12000,
         banner: './img/baner/all.jpg',
      },

      // {
      //    name: 'Americans',
      //    id: 30,
      //    model: 'Cadillac Escalade',
      //    year: '2007-2013',
      //    price: 12000,
      // },
   ],
];

/*
const toyta = [
   {
      name: 'toyta',
      id: 1,
      model: 'Land Cruiser 95',
      year: '1990-1997',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 2,
      model: 'Land Cruiser 100-105 (Lx470)',
      year: '1997-2007',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 3,
      model: 'PRADO 120 (GX470)',
      year: '2002-2009',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 4,
      model: 'PRADO 150 (GX460)',
      year: '2009-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 5,
      model: 'Land Cruiser 200',
      year: '2008-2021',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 6,
      model: 'Land Cruiser 300',
      year: '2021-',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 7,
      model: 'Camry 70',
      year: '2017-2019',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 8,
      model: 'Camry 50-55 usa',
      year: '1990-1997',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 9,
      model: 'Camry 50-55',
      year: '2011-2017',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 10,
      model: 'Camry 40-45',
      year: '2006-2011',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 11,
      model: 'Camry 30-35',
      year: '2001-2006',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 12,
      model: 'Camry 20-25',
      year: '1994-2001',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 13,
      model: 'Camry 10-15',
      year: '1991-1996',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 14,
      model: 'HILUX',
      year: '2004-2015',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 15,
      model: 'Fortuner',
      year: '2004-2015',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 16,
      model: 'HILUX',
      year: '2015-2022',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 17,
      model: 'Fortuner',
      year: '2020-2022',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 18,
      model: 'AVALON 05',
      year: '2005-2012',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 19,
      model: 'T.AVALON 12',
      year: '2012-2017',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 20,
      model: 'Avensis 03',
      year: '2003-2008',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 21,
      model: 'Avensis 09',
      year: '2009-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 22,
      model: 'ALPHARD 02',
      year: '2002-2008',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 23,
      model: 'ALPHARD 2008',
      year: '2008-2015',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 24,
      model: 'ALPHARD 2022',
      year: '2016-2023',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 25,
      model: 'Highlander',
      year: '2001-2007',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 26,
      model: 'Highlander',
      year: '2007-2013',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 27,
      model: 'Land Cruiser 95',
      year: '1990-1997',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 28,
      model: 'Highlander',
      year: '2013-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 29,
      model: 'Kluger',
      year: '2013-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 30,
      model: 'Highlander 20',
      year: '2020-2021',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 31,
      model: '4Runner',
      year: '2002-2009',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 32,
      model: '4Runner',
      year: '2009-2019',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 33,
      model: 'RAV-4',
      year: '2005-2012',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 34,
      model: 'RAV-4',
      year: '2013-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 35,
      model: 'RAV-4',
      year: '2018-2021',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 36,
      model: 'COROLLA E120',
      year: '2000-2006',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 37,
      model: 'COROLLA E150',
      year: '2006-2013',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 38,
      model: 'COROLLA E160',
      year: '2013-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 39,
      model: 'COROLLA E170',
      year: '2013-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 40,
      model: 'COROLLA Е210 ',
      year: '2018-2020',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 41,
      model: 'SIENNA 03',
      year: '2003-2010',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 42,
      model: 'SIENNA 10',
      year: '2010-',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 43,
      model: 'Ipsum',
      year: '2001-2009',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 44,
      model: 'Fj Cruiser ',
      year: '2006-2016',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 45,
      model: 'hiace',
      year: '2004-2018',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 46,
      model: 'hiace ',
      year: '1990-1997',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 47,
      model: 'CARINA E',
      year: '1992-1998',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 48,
      model: ' CORONA ',
      year: '1992-1998',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 49,
      model: 'Windom XV30',
      year: '2001-2006',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 50,
      model: 'Estima',
      year: '2001-2006',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 51,
      model: 'Estima XR50 ',
      year: '2006 -',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 52,
      model: 'Tundra',
      year: '2007-',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 53,
      model: 'Tacoma',
      year: '',
      price: 12000,
   },
   {
      name: 'toyta',
      id: 54,
      model: 'Venza',
      year: '2008-2017',
      price: 12000,
   },
];
const lexus = [
   {
      name: 'lexus',
      id: 1,
      model: 'LX570',
      year: '2007-2018',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 2,
      model: 'es300-330',
      year: '2001-2006',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 3,
      model: 'WINDOM XV30',
      year: '2001-2006',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 4,
      model: 'es350',
      year: '2006-2012',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 5,
      model: 'es 12-18',
      year: '2012-2018',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 6,
      model: 'es 19-22',
      year: '2019-2022',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 7,
      model: 'gs300 (160)',
      year: '1997-2005',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 8,
      model: 'gs300-350 (190)',
      year: '2005-2012',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 9,
      model: 'gs 12-',
      year: '2012-',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 10,
      model: 'IS 06-12',
      year: '2006-2012',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 11,
      model: 'IS 13-16',
      year: '2013-2016',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 12,
      model: 'NX200',
      year: '2014-2020',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 13,
      model: 'NX300',
      year: '2014-2020',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 14,
      model: 'RX300 ',
      year: '1997-2003',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 15,
      model: 'RX 330',
      year: '2003-2009',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 16,
      model: 'RX 350',
      year: '2009-2016',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 17,
      model: 'LS460',
      year: '2006-',
      price: 12000,
   },
   {
      name: 'lexus',
      id: 1,
      model: 'LS430',
      year: '2000-2006',
      price: 12000,
   },
];
const mercedesBenz = [
   {
      name: 'mercedesbenz',
      id: 1,
      model: 'W 124 (E-class)',
      year: '1984-1995',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 2,
      model: 'W 140 (S-class)',
      year: '1991-1998',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 3,
      model: 'W 210 (E-class)',
      year: '1995-2002',
      price: 2000,
   },
   {
      name: 'mercedesbenz',
      id: 4,
      model: 'W 210 задний',
      year: '1995-2002',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 5,
      model: 'W 211 (E-class)',
      year: '2002-2009',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 6,
      model: 'W 212 (E-class)',
      year: '2009-2016',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 7,
      model: 'W 220 (S-class)',
      year: '1998-2005',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 8,
      model: 'W 221 (S-class)',
      year: '2005-2013',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 9,
      model: 'W 222 (S-class)',
      year: '2013-',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 10,
      model: 'W 202 (C-class)',
      year: '1993-2001',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 11,
      model: 'W 203 (C-class)',
      year: '2000-2007',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 12,
      model: 'W 204 (C-class)',
      year: '2004-2014',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 13,
      model: 'GLS',
      year: '2006-2012',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 14,
      model: 'Gelendewagen (G-class)',
      year: '1979-2005',
      price: 12000,
   },
   {
      name: 'mercedesbenz',
      id: 15,
      model: '	A170',
      year: '',
      price: 12000,
   },
];
const bmw = [
   {
      name: 'bmw',
      id: 1,
      model: 'X5 E53',
      year: '1996-2006',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 2,
      model: 'X5 Е70',
      year: '2006-2013',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 3,
      model: 'E34',
      year: '1992-1996',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 4,
      model: 'E38',
      year: '1994-2001',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 5,
      model: 'E39',
      year: '1995-2003',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 6,
      model: 'E46',
      year: '1998-2007',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 7,
      model: 'E60',
      year: '2002-2010',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 8,
      model: 'E61',
      year: '2002-2010',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 9,
      model: 'E65',
      year: '2001-2008',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 10,
      model: 'E66',
      year: '2001-2008',
      price: 12000,
   },
   {
      name: 'bmw',
      id: 11,
      model: 'F30',
      year: '2012-2016',
      price: 12000,
   },
];
const audi = [
   {
      name: 'audi',
      id: 1,
      model: '100',
      year: '1991-1997',
      price: 12000,
   },
   {
      name: 'audi',
      id: 2,
      model: 'A6 (C4)',
      year: '1991-1997',
      price: 12000,
   },
   {
      name: 'audi',
      id: 3,
      model: 'A8',
      year: '1994-2002',
      price: 12000,
   },
   {
      name: 'audi',
      id: 4,
      model: 'Q7',
      year: '2006-2015',
      price: 12000,
   },
   {
      name: 'audi',
      id: 5,
      model: 'A6 (C5)',
      year: '1997-2004',
      price: 12000,
   },
   {
      name: 'audi',
      id: 6,
      model: 'A6 (C6)',
      year: '2005-2011',
      price: 12000,
   },
   {
      name: 'audi',
      id: 7,
      model: '	Audi 80 b4',
      year: '',
      price: 12000,
   },
];
const kia = [
   {
      name: 'kia',
      id: 1,
      model: 'K7',
      year: '',
      price: 12000,
   },
   {
      name: 'kia',
      id: 2,
      model: 'K5',
      year: '2020',
      price: 12000,
   },
   {
      name: 'kia',
      id: 3,
      model: 'RIO',
      year: '2011-2017',
      price: 12000,
   },
   {
      name: 'kia',
      id: 4,
      model: 'RIO NEW',
      year: '2017-',
      price: 12000,
   },
   {
      name: 'kia',
      id: 5,
      model: 'SPORTAGE ',
      year: '2010-2016',
      price: 12000,
   },
   {
      name: 'kia',
      id: 6,
      model: 'SPORTAGE',
      year: '2016-2020',
      price: 12000,
   },
   {
      name: 'kia',
      id: 7,
      model: 'SPORTAGE NEW',
      year: '2021-2023',
      price: 12000,
   },
   {
      name: 'kia',
      id: 8,
      model: 'CADENZA',
      year: '2009-2016',
      price: 12000,
   },
   {
      name: 'kia',
      id: 9,
      model: 'SORENTO PRIME',
      year: '2014-2019',
      price: 12000,
   },
   {
      name: 'kia',
      id: 10,
      model: 'SORENTO',
      year: '2002-2009',
      price: 12000,
   },
   {
      name: 'kia',
      id: 11,
      model: 'SORENTO',
      year: '2009-2014',
      price: 12000,
   },
   {
      name: 'kia',
      id: 12,
      model: 'SORENTO ',
      year: '2020-',
      price: 12000,
   },
   {
      name: 'kia',
      id: 13,
      model: 'SOUL',
      year: '2014-2019',
      price: 12000,
   },
   {
      name: 'kia',
      id: 14,
      model: 'SOUL',
      year: '2020-2023',
      price: 12000,
   },
   {
      name: 'kia',
      id: 15,
      model: 'CEED',
      year: '2012-2018',
      price: 12000,
   },
   {
      name: 'kia',
      id: 16,
      model: 'CERATO II',
      year: '2008-2013',
      price: 12000,
   },
   {
      name: 'kia',
      id: 17,
      model: 'CERATO III',
      year: '2013-2017',
      price: 12000,
   },
   {
      name: 'kia',
      id: 18,
      model: 'CERATO IV',
      year: '2018-',
      price: 12000,
   },
   {
      name: 'kia',
      id: 19,
      model: 'OPTIMA',
      year: '2010-2016',
      price: 12000,
   },
   {
      name: 'kia',
      id: 20,
      model: 'OPTIMA NEW',
      year: '2016-',
      price: 12000,
   },
   {
      name: 'kia',
      id: 21,
      model: 'MOHAVE',
      year: '2008-',
      price: 12000,
   },
];
const hyundai = [
   {
      name: 'hyundai',
      id: 1,
      model: 'ACCENT',
      year: '2001-2010',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 2,
      model: 'ACCENT',
      year: '2010-2017',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 3,
      model: 'Accent NEW',
      year: '2017-',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 4,
      model: 'Elantra',
      year: '2010-2015',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 5,
      model: 'Avante',
      year: '2010-2015',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 6,
      model: 'Elantra',
      year: '2016-2020',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 7,
      model: 'Elantra',
      year: '2021',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 8,
      model: 'Grandeur',
      year: '2005-2009',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 9,
      model: 'GETZ',
      year: '2002-2011',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 10,
      model: 'Santa-fe ',
      year: '2006-2012',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 11,
      model: 'Santa-fe',
      year: '2012-2018',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 12,
      model: 'Santa-fe',
      year: '2019-2021',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 13,
      model: 'Palisade',
      year: '',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 14,
      model: 'Tucson',
      year: '2004-2009',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 15,
      model: 'TUCSON-IX35',
      year: '2009-2015',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 16,
      model: 'Tucson',
      year: '2015-2020',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 17,
      model: 'Tucson  ',
      year: '2021-2022',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 18,
      model: 'Sonata',
      year: '2001-2004',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 19,
      model: 'Sonata',
      year: '2004-2008',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 20,
      model: 'Sonata',
      year: '2009-2014',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 21,
      model: 'Sonata',
      year: '2014-2019',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 22,
      model: 'Sonata',
      year: '2019-2021',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 23,
      model: 'I40',
      year: '2011-2019',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 24,
      model: 'CRETA',
      year: '2015-2019',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 25,
      model: 'Creta ',
      year: '2021',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 26,
      model: 'H1 Starex',
      year: '1997-2004',
      price: 12000,
   },
   {
      name: 'hyundai',
      id: 27,
      model: 'H1 Starex',
      year: '1996-н.в.',
      price: 12000,
   },
];
const honda = [
   {
      name: 'honda',
      id: 1,
      model: 'ODYSSEY',
      year: '2005-2010',
      price: 12000,
   },
   {
      name: 'honda',
      id: 2,
      model: 'ODYSSEY',
      year: '2011-',
      price: 12000,
   },
   {
      name: 'honda',
      id: 3,
      model: 'ELYSION',
      year: '',
      price: 12000,
   },
   {
      name: 'honda',
      id: 4,
      model: 'CRV',
      year: '1995-2001',
      price: 12000,
   },
];
const mitsubishi = [
   {
      name: 'mitsubishi',
      id: 1,
      model: 'Delica',
      year: '',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 2,
      model: 'Pajero 2',
      year: '1991-2000',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 3,
      model: 'Pajero 3',
      year: '1999-2006',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 4,
      model: 'Pajero sport',
      year: '2008-2016',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 5,
      model: 'Pajero sport',
      year: '2019-2022',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 6,
      model: 'Montero sport',
      year: '2019-2022',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 7,
      model: 'Montero sport',
      year: '1997-2004',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 8,
      model: 'Nativa',
      year: '1997-2004',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 9,
      model: 'L200',
      year: '2019-2022',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 10,
      model: 'Outlander',
      year: '',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 11,
      model: 'Outlander2',
      year: '2013-2020',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 12,
      model: 'ASX',
      year: '2010-2019',
      price: 12000,
   },
   {
      name: 'mitsubishi',
      id: 13,
      model: 'Lancer',
      year: '2007-2017',
      price: 12000,
   },
];
const nissan = [
   {
      name: 'nissan',
      id: 1,
      model: 'Teana j32',
      year: '2008-2014',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 2,
      model: 'Teana j31',
      year: '2003-2008',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 3,
      model: 'Teana j33',
      year: '',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 4,
      model: 'TIDA',
      year: '',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 5,
      model: 'maxima A32',
      year: '1994-2000',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 6,
      model: 'Cefiro',
      year: '1994-2000',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 7,
      model: 'Infiniti I30	',
      year: '1994-2000',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 8,
      model: 'maxima A33',
      year: '2000-2006',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 9,
      model: 'almera classic ',
      year: '2006-2012',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 10,
      model: 'Almera G15',
      year: '2012-',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 11,
      model: 'Patrol Y61',
      year: '1997-2004',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 12,
      model: 'Patrol Y62',
      year: '2010-2019',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 13,
      model: 'QX 56',
      year: '2010-2013',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 14,
      model: 'QX 80',
      year: '2013-2019',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 15,
      model: 'ARMADA',
      year: '2003-2015',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 16,
      model: 'QX56',
      year: '2004-2010',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 17,
      model: 'Pathfinder R51',
      year: '2005-2014',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 18,
      model: 'Qashqai 21',
      year: '2021-',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 19,
      model: 'QUEST',
      year: '2021-',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 20,
      model: 'Sentra',
      year: '2021-',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 21,
      model: 'X-Terra',
      year: '2005-2015',
      price: 12000,
   },
   {
      name: 'nissan',
      id: 22,
      model: 'X-Trail',
      year: '2007-2014',
      price: 12000,
   },
];
const volkswagen = [
   {
      name: 'volkswagen',
      id: 1,
      model: 'POLO',
      year: '2010-2018',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 2,
      model: 'POLO NEW',
      year: '2019-2021',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 3,
      model: 'PASSAT B3/B4',
      year: '1988-1996',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 4,
      model: 'PASSAT B5',
      year: '1996-2005',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 5,
      model: 'PASSAT B6',
      year: '2005-2010',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 6,
      model: 'TOUAREG',
      year: '2002-2010',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 7,
      model: 'PORSCHE',
      year: '2002-2010',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 8,
      model: 'CAYENNE',
      year: '2002-2010',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 9,
      model: ' GOLF 3',
      year: '1991-2002',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 10,
      model: ' GOLF 4',
      year: '1997-2010',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 11,
      model: '',
      year: '',
      price: 12000,
   },
   {
      name: 'volkswagen',
      id: 12,
      model: 'PASSAT B4',
      year: '1988-1996',
      price: 12000,
   },
];
const renault = [
   {
      name: 'renault',
      id: 1,
      model: 'Duster',
      year: '2009-',
      price: 12000,
   },
   {
      name: 'renault',
      id: 2,
      model: '	Logan',
      year: '2012-',
      price: 12000,
   },
];
const skoda = [
   {
      name: 'skoda',
      id: 1,
      model: 'RAPID',
      year: '2012-',
      price: 12000,
   },
   {
      name: 'skoda',
      id: 2,
      model: 'OCTAVIA  A5',
      year: '2004-2013',
      price: 12000,
   },
   {
      name: 'skoda',
      id: 3,
      model: 'OCTAVIA  A7',
      year: '2013-2017',
      price: 12000,
   },
   {
      name: 'skoda',
      id: 4,
      model: 'SUPERB',
      year: '2008-2015',
      price: 12000,
   },
];
const chevralet = [
   {
      name: 'chevralet',
      id: 1,
      model: 'Cruze',
      year: '2008-2015',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 2,
      model: 'TAHOE',
      year: '',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 3,
      model: 'EQUINOX',
      year: '2021',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 4,
      model: 'ONIX',
      year: '',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 5,
      model: 'Niva',
      year: '2002-',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 6,
      model: 'Captiva',
      year: '2006-',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 7,
      model: 'Aveo T250',
      year: '',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 8,
      model: 'Ravon R3',
      year: '',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 9,
      model: 'Malibu',
      year: '2011-2019',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 10,
      model: 'Cobalt',
      year: '2012-2017',
      price: 12000,
   },
   {
      name: 'chevralet',
      id: 11,
      model: 'RAVON R4',
      year: '2012-2017',
      price: 12000,
   },
];
const lada = [
   {
      name: 'lada',
      id: 1,
      model: '2114-2115',
      year: '2001-2013',
      price: 12000,
   },
   {
      name: 'lada',
      id: 2,
      model: '2107',
      year: '1982-2012',
      price: 12000,
   },
   {
      name: 'lada',
      id: 3,
      model: 'Largus',
      year: '2012-',
      price: 12000,
   },
   {
      name: 'lada',
      id: 4,
      model: 'Granta',
      year: '2011-2017',
      price: 12000,
   },
   {
      name: 'lada',
      id: 5,
      model: 'Калина',
      year: '2004-2018',
      price: 12000,
   },
   {
      name: 'lada',
      id: 6,
      model: 'Нива',
      year: '1977-2018',
      price: 12000,
   },
   {
      name: 'lada',
      id: 7,
      model: 'Нива Урбан',
      year: '1977-2018',
      price: 12000,
   },
   {
      name: 'lada',
      id: 8,
      model: 'Vesta',
      year: '2015-',
      price: 12000,
   },
   {
      name: 'lada',
      id: 9,
      model: 'X-RAY',
      year: '2015-',
      price: 12000,
   },
   {
      name: 'lada',
      id: 10,
      model: 'Газель Бизнес',
      year: '1994-2013',
      price: 14000,
   },
   {
      name: 'lada',
      id: 11,
      model: 'Газель NEXT',
      year: '2013-н.в.',
      price: 14000,
   },
   {
      name: 'lada',
      id: 12,
      model: 'УАЗ таблетка',
      year: '',
      price: 12000,
   },
   {
      name: 'lada',
      id: 13,
      model: 'УАЗ ПАТРИОТ',
      year: '',
      price: 12000,
   },
];
const remain = [
   {
      name: 'remain',
      id: 1,
      model: 'EXEED LX',
      year: '2021-2023',
      price: 12000,
   },
   {
      name: 'remain',
      id: 2,
      model: '	EXEED VX',
      year: '2021-2023',
      price: 12000,
   },
   {
      name: 'remain',
      id: 3,
      model: 'Subaru Outback 09',
      year: '2009-2014',
      price: 12000,
   },
   {
      name: 'remain',
      id: 4,
      model: 'Subaru Outback 15',
      year: '2015-2020',
      price: 12000,
   },
   {
      name: 'remain',
      id: 5,
      model: 'Subaru Tribecca	',
      year: '2005-2014',
      price: 12000,
   },
   {
      name: 'remain',
      id: 6,
      model: 'Subaru forester 08',
      year: '	2008-2012',
      price: 12000,
   },
   {
      name: 'remain',
      id: 7,
      model: 'Subaru forester 12',
      year: '2012-2018',
      price: 12000,
   },
   {
      name: 'remain',
      id: 8,
      model: 'Subaru forester 18',
      year: '2018',
      price: 12000,
   },
   {
      name: 'remain',
      id: 9,
      model: 'Cadillac Escalade',
      year: '2002-2006',
      price: 12000,
   },
   {
      name: 'remain',
      id: 10,
      model: 'Cadillac Escalade',
      year: '2007-2013',
      price: 12000,
   },
   {
      name: 'remain',
      id: 11,
      model: 'Chevralet Suburban',
      year: '2007-2013',
      price: 12000,
   },
   {
      name: 'remain',
      id: 12,
      model: 'Chevralet Tahoe',
      year: '2007-2013',
      price: 12000,
   },
   {
      name: 'remain',
      id: 13,
      model: 'GMC Yukon',
      year: '2007-2013',
      price: 12000,
   },
   {
      name: 'remain',
      id: 14,
      model: 'Cadillac Escalade ',
      year: '2015-',
      price: 12000,
   },
   {
      name: 'remain',
      id: 15,
      model: 'Chery 7-8 PRO',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 16,
      model: 'Jac S5',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 17,
      model: 'Range Rover',
      year: '2002-2012',
      price: 12000,
   },
   {
      name: 'remain',
      id: 18,
      model: 'INFINITY FX35/45',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 19,
      model: 'Hammer H2',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 20,
      model: '	Mazda MPV',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 21,
      model: 'MAZDA 6',
      year: '2002-2007',
      price: 12000,
   },
   {
      name: 'remain',
      id: 22,
      model: 'MAZDA 626 cronus',
      year: '	1997-2002',
      price: 12000,
   },
   {
      name: 'remain',
      id: 23,
      model: 'MAZDA 626 ',
      year: '1991',
      price: 12000,
   },
   {
      name: 'remain',
      id: 24,
      model: 'MAZDA птичка',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 25,
      model: 'LIFAN х60',
      year: '2012-2016',
      price: 12000,
   },
   {
      name: 'remain',
      id: 26,
      model: 'Nexia 1-2',
      year: '1994-2016',
      price: 12000,
   },
   {
      name: 'remain',
      id: 27,
      model: 'GREAT WALL',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 28,
      model: 'Gentra',
      year: '2013-2016',
      price: 12000,
   },
   {
      name: 'remain',
      id: 29,
      model: '	Geely Emgrand (кроссовер)',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 30,
      model: 'Cadillac Escalade',
      year: '2007-2013',
      price: 12000,
   },
   {
      name: 'remain',
      id: 31,
      model: 'OPEL ZAFIRA A',
      year: '1999-2005',
      price: 12000,
   },
   {
      name: 'remain',
      id: 32,
      model: 'OPEL ZAFIRA B',
      year: '2005-2011',
      price: 12000,
   },
   {
      name: 'remain',
      id: 33,
      model: '',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 34,
      model: 'OPEL ASTRA G',
      year: '',
      price: 12000,
   },
   {
      name: 'remain',
      id: 35,
      model: 'Opel Vectra',
      year: '1988-1995',
      price: 12000,
   },
   {
      name: 'remain',
      id: 36,
      model: 'Opel Vectra',
      year: '1995-2002',
      price: 12000,
   },
];
*/
